### ISSUE TITLE
[JOSS] Installation issues

### ISSUE THREAD

**Issue by effigies** [McMasterRS/LFSpy#1]
If I create a new environment, I can install `LFSpy` but not import it.

```
In [1]: import LFSpy                                                                                
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-fc0c0f3b939d> in <module>
----> 1 import LFSpy

/System/Volumes/Data/anaconda3/envs/lfspy/lib/python3.7/site-packages/LFSpy/__init__.py in <module>
----> 1 from .LFS import *

/System/Volumes/Data/anaconda3/envs/lfspy/lib/python3.7/site-packages/LFSpy/LFS.py in <module>
     27 #==========================================================================
     28 
---> 29 import numpy as np
     30 from scipy.io import loadmat
     31 from scipy.optimize import linprog

ModuleNotFoundError: No module named 'numpy'
```

To resolve this, dependencies should be passed to the package with `install_requires`, e.g.:

```Python
setup(
    ...,
    install_requires=['numpy>=1.14', 'scipy>=1.1', 'scikit-learn>=0.18.1']
    ...,
    )
```

If possible, it's good to specify the minimum versions that work. If somebody tries to install LFSpy into an existing environment that has too-old numpy, then it will not be upgraded. At best, they'll report the issue and you can resolve it by having them upgrade. At worst, they won't report it and will not use your package, or you might spend a lot of time trying to reproduce the error before realizing it's a version mismatch.

I chose 1.14 based on [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). The scipy and scikit-learn versions are just examples. They're sufficiently old that if your code works as expected on them, you can probably use them without causing version conflicts. Otherwise, try to find the oldest release that works.

**Comment by tmudway** [comment]
Went with your recommendations for the package versions with the exception of scikit-learn, where I had issues getting 0.18.1 to work so we went with 0.18.2. Updated version should be on pypi shortly.

Thanks!
