### ISSUE TITLE
[JOSS] Invalid imports in demo/test.py

### ISSUE THREAD

**Issue by effigies** [McMasterRS/LFSpy#2]
Installing with:

```Shell
pip install numpy scipy scikit-learn LFSpy
```

Trying to run:

```Python
In [5]: from LFSpy import LocalFeatureSelection                                                     

In [6]: lfs = LocalFeatureSelection(alpha=19, 
   ...: gamma=0.2, tau=2, sigma=1, n_beta=20, nrrp=2000, knn=1)

In [9]: from LFSpy.demo import training_data, training_labels                                       
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-1a499d28ba53> in <module>
----> 1 from LFSpy.demo import training_data, training_labels

/System/Volumes/Data/anaconda3/envs/lfspy/lib/python3.7/site-packages/LFSpy/demo.py in <module>
      1 from scipy.io import loadmat
----> 2 from LFS import LocalFeatureSelection
      3 from sklearn.pipeline import Pipeline
      4 
      5 mat = loadmat('./matlab_Data')

ModuleNotFoundError: No module named 'LFS'
```

The issue here is that `LFS` is a relative import. It will work if you're currently in that directory, but has issues if you're trying to import it from another module within the package.

To resolve it, change the imports to `from .LFS import LocalFeatureSelection`.

This is assuming you want `LFSpy.test` and `LFSpy.demo` to be usable from the package. If not, then I would recommend moving them to the root directory.

----

There's an additional issue with loading the test data, but resolving it will depend on how you want these modules exposed.

**Comment by tmudway** [comment]
@cooko-mcmaster modified the test files to use pytest and we updated the files (and the test data) accordingly

Thanks!
